spring:
  profiles:
    active: ${ACTIVE_SPRING_PROFILE}
    default: test

  application:
    name: movieapp

  data:
    mongodb:
      #      host: localhost
      #      port: 27017
      #      database: movieapp
      #      username: movieapp
      #      password: fnwM<Sj^%CDyc@
      #      auto-index-creation: true
      uri: ${MONGO_URI}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GB_CLIENT_ID}
            client-secret: ${GB_CLIENT_SECRET}

server:
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        security: trace
