name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GB_CLIENT_ID: ${{ secrets.GB_CLIENT_ID }}
      GB_CLIENT_SECRET: ${{ secrets.GB_CLIENT_SECRET }}
      ACTIVE_SPRING_PROFILE: ${{ secrets.ACTIVE_SPRING_PROFILE }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          export ACTIVE_SPRING_PROFILE=prod;MONGO_URI=${{ secrets.MONGO_URI }}
           mvn clean -B package --file pom.xml -e -X -DskipTests
      - name: Maven dependency tree
        run: mvn dependency:tree
