name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GB_CLIENT_ID: ${{ secrets.GB_CLIENT_ID }}
      GB_CLIENT_SECRET: ${{ secrets.GB_CLIENT_SECRET }}
      ACTIVE_SPRING_PROFILE: ${{ secrets.ACTIVE_SPRING_PROFILE }}

    steps:
      - uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '8.0'

      - name: Create MongoDB User
        run: |
          mongo --eval 'db.createUser({
            user: "movieapp",
            pwd: "fnwM<Sj^%CDyc@",
            roles: [{ role: "readWrite", db: "movieapp" }]
          })' --authenticationDatabase "admin"

      - name: Set up MongoDB URI
        run: echo "MONGO_URI=mongodb://movieapp:fnwM<Sj^%CDyc@@localhost:27017/movieapp" >> $GITHUB_ENV

      - name: Check MongoDB connection
        run: |
          echo "Checking MongoDB connection..."
          nc -zv localhost 27017

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean -B package --file pom.xml -e -X

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Maven dependency tree
        run: mvn dependency:tree
