name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GB_CLIENT_ID: ${{ secrets.GB_CLIENT_ID }}
      GB_CLIENT_SECRET: ${{ secrets.GB_CLIENT_SECRET }}
      ACTIVE_SPRING_PROFILE: test
      MONGO_URI: ${{ secrets.MONGO_URI }}

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Build with Maven and Run Tests
        run: mvn clean verify -B -e -X -DskipTests=false

  build:
    runs-on: ubuntu-latest

    env:
      GB_CLIENT_ID: ${{ secrets.GB_CLIENT_ID }}
      GB_CLIENT_SECRET: ${{ secrets.GB_CLIENT_SECRET }}
      ACTIVE_SPRING_PROFILE: ${{ secrets.ACTIVE_SPRING_PROFILE }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean -B package --file pom.xml -e -X -DskipTests
      - name: Maven dependency tree
        run: mvn dependency:tree
